version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - DOCKERHUB_USERNAME

jobs:
  build:
    environment:
      IMAGE_NAME: jimareed/slideshow-editor
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: |
            docker build --tag myapp .
      - run:
          name: Docker Push
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            APP=slideshow-editor
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag myapp $DOCKERHUB_USERNAME/$APP:$TAG
            docker tag myapp $DOCKERHUB_USERNAME/$APP:latest
            docker push $DOCKERHUB_USERNAME/$APP:$TAG
            docker push $DOCKERHUB_USERNAME/$APP:latest
